version: '3'
services:
  web:
    image: java_springv1
    build: .
    ports:
      - "8085:8080"
    volumes:
      - persistent_volume:/app/volumes
volumes:
  persistent_volume:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/ubuntu/spring_portfolio/volumes
