version: '3'
services:
  web:
    image: java_springv1_8679
    restart: on-failure
    build: .
    ports:
      - "8679:8679"
    volumes:
      - persistent_volume:/app/volumes
volumes:
  persistent_volume:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/ubuntu/T8679_springjava/volumes
